### ISSUE TITLE
DflDataModule does not exists

### ISSUE THREAD

**Issue by AlessioDelConte** [xu-shi-jie/idp-elm#2]
Hello,
I was trying to train the models, and I get this error:

```
Traceback (most recent call last):
  File "/app/models/train.py", line 4, in <module>
    from dataloader import (ApodDataModule, CaidDataModule, DeepDisoBindDataModule,
ImportError: cannot import name 'DflDataModule' from 'dataloader' (/app/models/dataloader.py)
```
Indeed, there is no class called `DflDataModule` in the `dataloader` file.

Another error occurred while running the encoding of the sequences:

```
Traceback (most recent call last):
  File "/app/models/encoder.py", line 197, in <module>
    gen_embs(args.task)
  File "/app/models/encoder.py", line 174, in gen_embs
    dm = NetSurfP30DataModule(batch_size=1, num_workers=1)
  File "/app/models/dataloader.py", line 143, in __init__
    data = open('data/NetSurfP-3.0/Train_HHblits.txt').read().splitlines()
FileNotFoundError: [Errno 2] No such file or directory: 'data/NetSurfP-3.0/Train_HHblits.txt'
```

And as before, there is no directory called `NetSurfP-3.0` in the data directory

**Comment by xu-shi-jie** [comment]
@AlessioDelConte For prediction of disordered linker/protein-binding or IDP, please consider use our public available server at https://onodalab.ees.hokudai.ac.jp/idp-elm.

**Comment by AlessioDelConte** [comment]
That's not really an option for me, I need to execute the predictor locally and reproduce your results.
